title: Shards of the Library
email: your-email@example.com
description: >-
  Official developer blog and portal for Shards of the Library.
url: "https://JoeyStickDev.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/

collections:
  posts:
    output: true

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - RowData/
  - scripts/
  - README.md
  - .antigravityignore
